#############################################################################
# Makefile for building: libteam1.so.1.0.0
# Generated by qmake (3.1) (Qt 5.10.1)
# Project:  ../../Files/team1.pro
# Template: lib
# Command: /media/yevhenii/Work/QT/5.10.1/gcc_64/bin/qmake -o Makefile ../../Files/team1.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DTEAM1_LIBRARY -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I../../Files -I. -I../../../../QT/5.10.1/gcc_64/include -I../../../../QT/5.10.1/gcc_64/include/QtCore -I. -I../../../../QT/5.10.1/gcc_64/mkspecs/linux-g++
QMAKE         = /media/yevhenii/Work/QT/5.10.1/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /media/yevhenii/Work/QT/5.10.1/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /media/yevhenii/Work/QT/5.10.1/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = team11.0.0
DISTDIR = /media/yevhenii/Work/Projects/Game/test/team1/.tmp/team11.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/media/yevhenii/Work/QT/5.10.1/gcc_64/lib -shared -Wl,-soname,libteam1.so.1
LIBS          = $(SUBLIBS) -L/media/yevhenii/Work/QT/5.10.1/gcc_64/lib -lQt5Core -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../../Files/team1.cpp \
		../../Files/class6_7.cpp \
		../../Files/class8_9.cpp \
		../../Files/class10.cpp 
OBJECTS       = team1.o \
		class6_7.o \
		class8_9.o \
		class10.o
DIST          = /media/yevhenii/QT/5.10.1/gcc_64/mkspecs/features/spec_pre.prf \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/common/unix.conf \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/common/linux.conf \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/common/sanitize.conf \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/common/gcc-base.conf \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/common/g++-base.conf \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/common/g++-unix.conf \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/qconfig.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/features/qt_functions.prf \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/features/qt_config.prf \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/features/spec_post.prf \
		../../Files/.qmake.stash \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/features/toolchain.prf \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/features/default_pre.prf \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/features/resolve_config.prf \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/features/default_post.prf \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/features/qml_debug.prf \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/features/warn_on.prf \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/features/qt.prf \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/features/resources.prf \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/features/moc.prf \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/features/unix/thread.prf \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/features/qmake_use.prf \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/features/file_copies.prf \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/features/testcase_targets.prf \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/features/exceptions.prf \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/features/yacc.prf \
		/media/yevhenii/QT/5.10.1/gcc_64/mkspecs/features/lex.prf \
		../../../Files/team1.pro ../../Files/team1.h \
		../../Files/team1_global.h \
		../../Files/class6_7.h \
		../../Files/class8_9.h \
		../../Files/class10.h ../../Files/team1.cpp \
		../../Files/class6_7.cpp \
		../../Files/class8_9.cpp \
		../../Files/class10.cpp
QMAKE_TARGET  = team1
DESTDIR       = 
TARGET        = libteam1.so.1.0.0
TARGETA       = libteam1.a
TARGET0       = libteam1.so
TARGETD       = libteam1.so.1.0.0
TARGET1       = libteam1.so.1
TARGET2       = libteam1.so.1.0


first: all
####### Build rules

$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)



staticlib: $(TARGETA)

$(TARGETA):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)

Makefile: ../../Files/team1.pro ../../../../QT/5.10.1/gcc_64/mkspecs/features/spec_pre.prf \
		../../../../QT/5.10.1/gcc_64/mkspecs/common/unix.conf \
		../../../../QT/5.10.1/gcc_64/mkspecs/common/linux.conf \
		../../../../QT/5.10.1/gcc_64/mkspecs/common/sanitize.conf \
		../../../../QT/5.10.1/gcc_64/mkspecs/common/gcc-base.conf \
		../../../../QT/5.10.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../../QT/5.10.1/gcc_64/mkspecs/common/g++-base.conf \
		../../../../QT/5.10.1/gcc_64/mkspecs/common/g++-unix.conf \
		../../../../QT/5.10.1/gcc_64/mkspecs/qconfig.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../QT/5.10.1/gcc_64/mkspecs/features/qt_functions.prf \
		../../../../QT/5.10.1/gcc_64/mkspecs/features/qt_config.prf \
		../../../../QT/5.10.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../../QT/5.10.1/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../QT/5.10.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../../QT/5.10.1/gcc_64/mkspecs/features/toolchain.prf \
		../../../../QT/5.10.1/gcc_64/mkspecs/features/default_pre.prf \
		../../../../QT/5.10.1/gcc_64/mkspecs/features/resolve_config.prf \
		../../../../QT/5.10.1/gcc_64/mkspecs/features/default_post.prf \
		../../../../QT/5.10.1/gcc_64/mkspecs/features/qml_debug.prf \
		../../../../QT/5.10.1/gcc_64/mkspecs/features/warn_on.prf \
		../../../../QT/5.10.1/gcc_64/mkspecs/features/qt.prf \
		../../../../QT/5.10.1/gcc_64/mkspecs/features/resources.prf \
		../../../../QT/5.10.1/gcc_64/mkspecs/features/moc.prf \
		../../../../QT/5.10.1/gcc_64/mkspecs/features/unix/thread.prf \
		../../../../QT/5.10.1/gcc_64/mkspecs/features/qmake_use.prf \
		../../../../QT/5.10.1/gcc_64/mkspecs/features/file_copies.prf \
		../../../../QT/5.10.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../../QT/5.10.1/gcc_64/mkspecs/features/exceptions.prf \
		../../../../QT/5.10.1/gcc_64/mkspecs/features/yacc.prf \
		../../../../QT/5.10.1/gcc_64/mkspecs/features/lex.prf \
		../../Files/team1.pro \
		../../../../QT/5.10.1/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile ../../Files/team1.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
../../../../QT/5.10.1/gcc_64/mkspecs/features/spec_pre.prf:
../../../../QT/5.10.1/gcc_64/mkspecs/common/unix.conf:
../../../../QT/5.10.1/gcc_64/mkspecs/common/linux.conf:
../../../../QT/5.10.1/gcc_64/mkspecs/common/sanitize.conf:
../../../../QT/5.10.1/gcc_64/mkspecs/common/gcc-base.conf:
../../../../QT/5.10.1/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../../QT/5.10.1/gcc_64/mkspecs/common/g++-base.conf:
../../../../QT/5.10.1/gcc_64/mkspecs/common/g++-unix.conf:
../../../../QT/5.10.1/gcc_64/mkspecs/qconfig.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_charts.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../QT/5.10.1/gcc_64/mkspecs/features/qt_functions.prf:
../../../../QT/5.10.1/gcc_64/mkspecs/features/qt_config.prf:
../../../../QT/5.10.1/gcc_64/mkspecs/linux-g++/qmake.conf:
../../../../QT/5.10.1/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../QT/5.10.1/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../../QT/5.10.1/gcc_64/mkspecs/features/toolchain.prf:
../../../../QT/5.10.1/gcc_64/mkspecs/features/default_pre.prf:
../../../../QT/5.10.1/gcc_64/mkspecs/features/resolve_config.prf:
../../../../QT/5.10.1/gcc_64/mkspecs/features/default_post.prf:
../../../../QT/5.10.1/gcc_64/mkspecs/features/qml_debug.prf:
../../../../QT/5.10.1/gcc_64/mkspecs/features/warn_on.prf:
../../../../QT/5.10.1/gcc_64/mkspecs/features/qt.prf:
../../../../QT/5.10.1/gcc_64/mkspecs/features/resources.prf:
../../../../QT/5.10.1/gcc_64/mkspecs/features/moc.prf:
../../../../QT/5.10.1/gcc_64/mkspecs/features/unix/thread.prf:
../../../../QT/5.10.1/gcc_64/mkspecs/features/qmake_use.prf:
../../../../QT/5.10.1/gcc_64/mkspecs/features/file_copies.prf:
../../../../QT/5.10.1/gcc_64/mkspecs/features/testcase_targets.prf:
../../../../QT/5.10.1/gcc_64/mkspecs/features/exceptions.prf:
../../../../QT/5.10.1/gcc_64/mkspecs/features/yacc.prf:
../../../../QT/5.10.1/gcc_64/mkspecs/features/lex.prf:
../../Files/team1.pro:
../../../../QT/5.10.1/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ../../Files/team1.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../../QT/5.10.1/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../../Files/team1.h ../../Files/team1_global.h ../../Files/class6_7.h ../../Files/class8_9.h ../../Files/class10.h $(DISTDIR)/
	$(COPY_FILE) --parents ../../Files/team1.cpp ../../Files/class6_7.cpp ../../Files/class8_9.cpp ../../Files/class10.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) $(TARGET0) $(TARGET1) $(TARGET2) $(TARGETA)
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../../QT/5.10.1/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../../../../QT/5.10.1/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

team1.o: ../../Files/team1.cpp ../../Files/team1.h \
		../../Files/team1_global.h \
		../../../../QT/5.10.1/gcc_64/include/QtCore/qglobal.h \
		../../../../QT/5.10.1/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../../QT/5.10.1/gcc_64/include/QtCore/qconfig.h \
		../../../../QT/5.10.1/gcc_64/include/QtCore/qtcore-config.h \
		../../../../QT/5.10.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../../../QT/5.10.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../../../QT/5.10.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../../QT/5.10.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../../../QT/5.10.1/gcc_64/include/QtCore/qsysinfo.h \
		../../../../QT/5.10.1/gcc_64/include/QtCore/qlogging.h \
		../../../../QT/5.10.1/gcc_64/include/QtCore/qflags.h \
		../../../../QT/5.10.1/gcc_64/include/QtCore/qatomic.h \
		../../../../QT/5.10.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../../../QT/5.10.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../../QT/5.10.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../../../QT/5.10.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../../QT/5.10.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../../QT/5.10.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../../../QT/5.10.1/gcc_64/include/QtCore/qmutex.h \
		../../../../QT/5.10.1/gcc_64/include/QtCore/qnumeric.h \
		../../../../QT/5.10.1/gcc_64/include/QtCore/qversiontagging.h \
		../../Files/class6_7.h \
		../../Files/class8_9.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o team1.o ../../Files/team1.cpp

class6_7.o: ../../Files/class6_7.cpp ../../Files/class6_7.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o class6_7.o ../../Files/class6_7.cpp

class8_9.o: ../../Files/class8_9.cpp ../../Files/class8_9.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o class8_9.o ../../Files/class8_9.cpp

class10.o: ../../Files/class10.cpp ../../Files/class10.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o class10.o ../../Files/class10.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib || mkdir -p $(INSTALL_ROOT)/usr/lib
	-$(QINSTALL_PROGRAM) $(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET)
	-$(SYMLINK) $(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET0)
	-$(SYMLINK) $(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET1)
	-$(SYMLINK) $(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET2)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET) 
	 -$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET0) 
	 -$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET1) 
	 -$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET2)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

